---
version: '3.9'

services:
  db:
    image: postgres:12
    stop_signal: SIGINT # Fast shutdown.
    ports:
      - 5325:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data:delegated
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    healthcheck:
      test: [CMD-SHELL, pg_isready -h localhost -p 5432 -U postgres]
      timeout: 30s
      interval: 5s
